#!/usr/bin/env bash
# Displays a list of currently running processes.
# must show all process for all users 
# Shows all processes, for all users, including those
# shows process hierarchy.

ps -a -x -u -f
