#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration
# displays Best School and then Hi on a new line.
# Set counter variable
counter=0

# Loop while counter is less than or equal to 10
while [ $counter -lt 10 ]
do
  # If counter is equal to 9, display "Best School" and then "Hi"
  if [ $counter -eq 9 ]
  then
	  echo "Hi"
  fi
  echo "Best School"
  (( counter ++ ))
done
